version: '3.1'
services:
  db:
    build: ./database/
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Europe/Vilnius
    volumes:
      - ts_auth:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  ts_auth:
